### ISSUE TITLE
无法接管浏览器下载

### ISSUE THREAD

**Issue by Haku271** [alexhua/Aria2-Manager#10]
几天用下来没有接管过浏览器下载，在扩展设置中也开启了拦截

**Comment by alexhua** [comment]
建议参考 alexhua/Aria2-Explorer#212

**Comment by Haku271** [comment]
我的扩展RPC都是http://localhost:6800/jsonrpc图标没有错误

l
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexhua/Aria2-Manager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月17日(星期二) 上午10:32
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexhua/Aria2-Manager] 无法接管浏览器下载 (Issue #10)





 
建议参考 alexhua/Aria2-Explorer#212

**Comment by alexhua** [comment]
> 我的扩展RPC都是http://localhost:6800/jsonrpc图标没有错误

大概率是设置问题，没有详细的复现步骤和背景信息，这个问题没法分析。
