### ISSUE TITLE
有人遇到开启 “监测Aria2下载状态” 闪烁的问题吗？

### ISSUE THREAD

**Issue by i-iooi-i** [alexhua/Aria2-Manager#2]
![动画](https://github.com/alexhua/Aria2-Manager/assets/1827701/1abda60b-8007-4ba2-9217-d6646471bce3)

好久之前的版本没有这个频闪问题。
链接域名就会频闪, 链接内网IP地址不会闪烁. (问题是以前链接域名也不会闪烁的)

似然不影响资源下载啥的，但是在浏览器栏这样一直规律闪烁，还是会让人很分心，😂
最近把图标从浏览器状态栏暂时隐藏了.

**Comment by alexhua** [comment]
有可能是你的远程服务器不支持websocket，你在扩展选项里把`任务状态通知`关了试试。

**Comment by i-iooi-i** [comment]
> 有可能是你的远程服务器不支持websocket，你在扩展选项里把`任务状态通知`关了试试。 PS：你这issue提错地方了。 下次提这里 [Aria2-Explorer](https://github.com/alexhua/aria2-explorer/issues)。

感谢大佬提醒,我在群晖的反向代理里面加了 WebSocket ,这个频闪的问题解决辣. 

嗯嗯, 刚才已经 Star Aria2-Explorer 啦, 感谢大佬的项目,炒鸡棒! 😽😽
