### ISSUE TITLE
商店版如何修改配置文件修改下载目录？

### ISSUE THREAD

**Issue by Giresharu** [alexhua/Aria2-Manager#4]
我通过 Listary 进行搜索找到了商店版的目录在 `C:\Program Files\WindowsApps\45919AlexHua.29853E39DCC26_1.2.0.0_x64__gbt8sgjjv031p\TaskBar` 下，但这个文件夹没有任何可编辑的权限，即使是 Administrator 也无法进行编辑。

另外，我希望 file-allocation 设为 falloc，这将需要以管理员权限启动 Aria2 Manager，但如何用管理员权限自动启动商店版呢？

希望能尽快提供解决办法，因为这两个问题，目前我仍然只能使用 Github 版

**Comment by alexhua** [comment]
不推荐直接改配置文件

可以通过在扩展配置页设置 **Download Location** 来设置 **下载目录**，自动拦截的时候会用到；也可以去扩展内置的 **AriaNG** 的`Aria2设置`里改，通过 **AriaNG** 创建任务的时候会用到。常用的 Aria2 配置都可以在 `Aria2设置` 里改，设置会保存。

文件预分配也可以去`Aria2设置`->`高级设置`里改。

用管理员权限自动启动Aria2-Manager，这好像做不到，即使可以，每次开机还得点下**确认**，不也和手动启动差不多么。

**Comment by Giresharu** [comment]
> 不推荐直接改配置文件
> 
> 可以通过在扩展配置页设置 **Download Location** 来设置 **下载目录**，自动拦截的时候会用到；也可以去扩展内置的 **AriaNG** 的`Aria2 设置`里改，通过 **AriaNG** 创建任务的时候会用到。常用的 Aria2 配置都可以在 `Aria2 设置` 里改，设置会保存。
> 
> 文件预分配也可以去`Aria2 设置`->`高级设置`里改。
> 
> 用管理员权限自动启动 Aria2-Manager，这好像做不到，即使可以，每次开机还得点下**确认**，不也和手动启动差不多么。

我之前使用的是任务计划以最高权限打开 exe 来做自动启动，不会弹UAC

**Comment by alexhua** [comment]
> 我之前使用的是任务计划以最高权限打开 exe 来做自动启动，不会弹UAC

刚才正好试了一下，你也可以用这个方法给商店版的**Aria2Manager.exe**建一个自启动任务计划以最高权限运行。地址就是你找到的这个地址。

**Comment by alexhua** [comment]
再提供一个简便的办法：
![屏幕截图 2024-03-02 012207](https://github.com/alexhua/Aria2-Manager/assets/1220458/1759f7fa-ecbd-4b10-9ffc-e677c66dbab4)

**Comment by alexhua** [comment]
**v1.3.0** 版的`aria2.conf`已经放到到了`%userprofile%/AppData/Local/Aria2 Manager/`下，用户可以直接修改。
