### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by selectfilesintolocalfromGitHub** [alexhua/Aria2-Manager#5]
1、如果处于权限目录，即便给了（两程序）管理员权限，依然不能写入会话文件，造成无法保存当前会话，退出即刻丢失。
2、任务栏的图标建议去除，原因是，没有任何防关闭进程的措施，一旦误关命令行窗口，直接进程结束，最大的问题就是，连带会话（已经写入会话文件的信息）也一并清空了，这个就是严总bug了。具体可以参阅下进程隐藏的参数。

**Comment by alexhua** [comment]
可以试试最新的[商店版](https://apps.microsoft.com/detail/Aria2%20Manager/9P5WQ68Q20WV?launch=true&cid=github)
