### ISSUE TITLE
商店版的，提两点需求。

### ISSUE THREAD

**Issue by ZhongMoDao** [alexhua/Aria2-Manager#7]
一个就是记住窗口位置和大小，每次启动改好的窗口大小都会重置。

第二就是导入种子之后，能不能先给选择哪些文件要下载，而不是先下载再暂停去选择文件？

**Comment by alexhua** [comment]
1. 这个后续会优化
2. 先展示再创建不好搞，目前可以点`手动开始下载`，再去选择文件。后续可能添加一个`创建并筛选`按钮，点完直接跳到筛选界面。

**Comment by alexhua** [comment]
Aria2-Manager v2.3.0  已经上架。
