### ISSUE TITLE
偶尔A2E调用无法打开文件夹

### ISSUE THREAD

**Issue by MC-dusk** [alexhua/Aria2-Manager#9]
win11，chrome浏览器，使用[Aria2-Explorer](https://github.com/alexhua/Aria2-Explorer)浏览器扩展，下载完后点击网页控制台具体下载任务的打开文件夹按钮（已提前注册A2M自定义的aria2协议）

有的时候打不开文件夹，或者打开后文件资源管理器是根目录，猜测可能是文件名不规范比如有空格特殊字符等导致，或者文件名太长，具体试了几次没看出规律。

**Comment by alexhua** [comment]
贴一个不能打开的文件名上来，好分析和测试。

**Comment by MC-dusk** [comment]
> 贴一个不能打开的文件名上来，好分析和测试。

https://www.bilibili.com/video/BV1rU4y1J785
